### ISSUE TITLE
 You attempted to remove a function listener which did not exist on the instance, which means it was an inherited prototype listener, or you attempted to remove it before it was added. Prototype function listeners have been deprecated, and attempting to remove a non-existent function listener this will error in the future. Transition Plan

### ISSUE THREAD

**Issue by schekin** [simplabs/ember-simple-auth#1728]
2 You attempted to remove a function listener which did not exist on the instance, which means it was an inherited prototype listener, or you attempted to remove it before it was added. Prototype function listeners have been deprecated, and attempting to remove a non-existent function listener this will error in the future. Transition Plan

When user devise.. by this is manual https://romulomachado.github.io/2015/09/28/using-ember-simple-auth-with-devise.html

**Comment by schekin** [comment]
now i am switch to doorkeeper from devise .... and have this is deprecation to..

**Comment by IgorKvasn** [comment]
looks like it has been fixed by #1725

**Comment by ncoden** [comment]
@richard-viney @marcoow 👋  I still have the depreciation warning with the latest version `1.8.0`.

Could you please release a new version with your latest fix https://github.com/simplabs/ember-simple-auth/commit/0ab8847ed94812c391f66f79c645127abd771f95#diff-69677503ba9258b8f9b3a51694d1dc60 ?

Thank you.

**Comment by richard-viney** [comment]
@ncoden Until there's a new release you can get the fix by specifying a version of "github:simplabs/ember-simple-auth#0ab8847" in your `package.json`.

**Comment by marcoow** [comment]
closing as it's fixed by #1725

**Comment by robclancy** [comment]
And why isn't the fix released?
