### ISSUE TITLE
Deprecation warnings on Ember 3.9 (computed property was just overriden)

### ISSUE THREAD

**Issue by krachtstefan** [simplabs/ember-simple-auth#1908]
As mentioned in issue https://github.com/simplabs/ember-simple-auth/issues/1799, there is stil one deprecation warning with Ember 3.9:

`DEPRECATION: The <(unknown):ember242>#_isFastBoot computed property was just overriden. This removes the computed property and replaces it with a plain value, and has been deprecated. If you want this behavior, consider defining a setter which does it manually.`

The stacktrace is referencing the following line

https://github.com/simplabs/ember-simple-auth/blob/76e0eacf94f1d1d4d1194b3ef93ceae0bc5e000e/addon/session-stores/adaptive.js#L130

**Comment by Turbo87** [comment]
@marcoow any idea how that could happen? setting a property on a freshly created `{}` object shouldn't cause any CPs to be overwritten 🤔

**Comment by marcoow** [comment]
Yes, we're still using the `isFastBoot` CP macro (e.g. https://github.com/simplabs/ember-simple-auth/blob/d6071274d0cb8e3855e24bf2687c1a6395379440/addon/session-stores/local-storage.js#L29) - that should be relatively easy to replace though as there should be no need for that to be a CP anyway

**Comment by Turbo87** [comment]
@marcoow I think the problem here is not that it's a CP, the problem is that we're overriding a property from a subclass with something potentially unrelated. we shouldn't be overriding at all without a good reason.

**Comment by josemarluedke** [comment]
What is the reason for having this set `options._isFastBoot = false` assigned here anyway? Could that be just removed?

**Comment by bhabanipetnet** [comment]
hello. Could we have an update in this `#_isFastBoot computed property` issue?

**Comment by robclancy** [comment]
This was reported in 3.9 and now we are on 3.13. Ember doesn't even release that often.

**Comment by vmalloc** [comment]
How easy is it to fix? I can try and craft a PR but I'm not 100% sure I understand what this needs to change to...

**Comment by jordpo** [comment]
Also wondering about the status of this. Thanks!

**Comment by devotox** [comment]
This was not fixed in any of the new versions.

After tracing the problem is that `options._isFastBoot` is passed into the `createStore` functions

**Comment by vmalloc** [comment]
Just got this again after trying to upgrade to 2.0.0:
```
deprecate.js:120 DEPRECATION: The <(unknown):ember228>#_isFastBoot computed property was just overriden. This removes the computed property and replaces it with a plain value, and has been deprecated. If you want this behavior, consider defining a setter which does it manually. [deprecation id: computed-property.override] See https://emberjs.com/deprecations/v3.x#toc_computed-property-override for more details.
```

**Comment by luketheobscure** [comment]
I can confirm that this exists in 2.0.0. The problem code is here: https://github.com/simplabs/ember-simple-auth/blob/76e0eacf94f1d1d4d1194b3ef93ceae0bc5e000e/addon/session-stores/adaptive.js#L145

**Comment by robclancy** [comment]
I upgraded to 2.1.0 from the 1.x series and figured surely this is fixed. But no. I don't understand.

**Comment by tombenj** [comment]
This issue is still not fixed and causes never-ending pending authentication requests when using docker containers.

**Comment by robclancy** [comment]
Yep I'm don't with this package. Going to roll our own stuff. It was never
"simple" in the first place anyway.

**Comment by vmalloc** [comment]
@marcoow I’d like to help fix this issue, but need some guidance on where to start... It is a shame for this to still be a nuisance in the pretty much only decent ember auth library...

**Comment by tombenj** [comment]
Update - this issue completely renders simple-auth useless. I think that at this stage a warning should be placed in the main README that ember-simple-auth doesn't work with newer Ember versions.

**Comment by vmalloc** [comment]
@tombenj explain? Why does it render it useless?

**Comment by marcoow** [comment]
@vmalloc I have a branch for that here that I didn't find the time yet to complete/release: https://github.com/simplabs/ember-simple-auth/tree/fix-cp-override I'm actually not sure what's missing (might actually be complete) - would be awesome if you'd find the time to revisit that and open a PR!

**Comment by robclancy** [comment]
It's just embarrassing that this hasn't been fixed at this point.

**Comment by jfschaff** [comment]
I'm also having this issue. In my case, it seems like the `oauth2-implicit-grant-callback-route-mixin` does not behave as it used to, which makes the whole OAuth 2 process fail.

I tried the following configurations:
```
Ember                : 3.14.3
Ember Data           : 3.14.1
Ember Bootstrap      : 3.1.0
Ember Django Adapter : 2.1.1
Ember Simple Auth    : 1.9.2
```
and
```
Ember                : 3.14.3
Ember Data           : 3.14.1
Ember Bootstrap      : 3.1.0
Ember Django Adapter : 2.1.1
Ember Simple Auth    : 2.1.1
```

I'm willing to help fix that. @marcoow I will start by trying with your branch.

**Comment by robclancy** [comment]
This issue was created July 21. Ember octane has been released. A maintainer said it would be easy to fix. But asks for someone else to finish a branch made. 

wtf

**Comment by marcoow** [comment]
@vmalloc @jfschaff: thanks for the offer to help! There's a WIP PR for this: #2076. All deprecations in app/addon code should be fixed but there are some left in ESA's own test code which we should be able to fix as well.

**Comment by vmalloc** [comment]
@marcoow thanks! Sorry I didn't get to that until now - has been a crazy month for me. 
Can I help with the PR somehow? I'm not intimately familiar with the tests but assuming it's fairly narrowed-down I can try my luck with it....

**Comment by marcoow** [comment]
I haven’t had a closer look at the failing tests yet. I think the main thing to do to remove the remaining depreciations will be refactoring the tests for the adaptive store and the shared specs.

**Comment by robclancy** [comment]
Here is another comment for you to delete. Why tf is this still a thing? Is this package not used by the maintainers anymore so they don't care? 

Ember 3.9 was released 9 months ago.

**Comment by luketheobscure** [comment]
@robclancy - You seem to have a lot of passion. Why not channel it into contributing to some open source projects? The beauty of open source is that if something really bothers us, we can just fix it ourselves!

Also, I'm using Ember 3.15 and Ember SImple Auth works great for me. I do have a deprecation warning in the Ember inspector, but that hardly renders this unusable. Maybe the problem lies elsewhere in your stack?

**Comment by jfschaff** [comment]
> Here is another comment for you to delete. Why tf is this still a thing? Is this package not used by the maintainers anymore so they don't care?

I love the smell of hateful comments in the morning! Very productive!

![image](https://user-images.githubusercontent.com/25389614/73055696-a9e6af80-3e8d-11ea-88f1-76da97765a12.png)

**Comment by marcoow** [comment]
#2076 should finally be ready and fix this

**Comment by marcoow** [comment]
Thanks for everyone who stayed calm although this took a bit ❤️ 😉

**Comment by williamhaley** [comment]
For the sake of SEO and future explorers, the deprecation message is similar (yet oh-so slightly different) as of Ember 3.17 (maybe earlier, but I just noticed it there).

> _isFastBoot computed property was just overrid**d**en

Emphasis mine. Seems a [typo was fixed in core Ember](https://github.com/emberjs/ember.js/pull/18645/files/900f1707b637e4d43ff8030bc0df94bb4cca50b3) for `overriden` -> `overridden`. Not directly related to this issue, but also, this issue was the first that came up for me while generally searching for `computed property was just overridden`, even before the [general Ember explanation](https://deprecations.emberjs.com/v3.x/#toc_computed-property-override).
